### ISSUE TITLE
Secure the proctorlink in moodle

### ISSUE THREAD

**Issue by rohansharmasitoula** [talview/moodle-local_proview#41]
**Description**: Secure the proctorlink in moodle with a token appended to the url for embedded view.
**Current Behaviour:**  : The proctor link which is displayed currently in the moodle application after a student attempts an exam is not secured. 
**Expected** :  Once the proctor link is clicked, the secure token has to be appended to the url.

**Associated PRs:** 
- [x] secure proctor link #42 

- [x] talview/moodle-local_proview_api#11

- [x] add proctortype column in local_proview #44

**Comment by Anil-R07** [comment]
@rohansharmasitoula I Tested on Moodle for all the types, the token is getting appended to the proctor link
